/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package profilesection;

import javax.swing.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author seang
 */
public class RegisterGUI extends javax.swing.JFrame {

    
    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {
      
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        registerBTN = new javax.swing.JButton();
        userNameRegiserLBL = new javax.swing.JLabel();
        emailRegisterLBL = new javax.swing.JLabel();
        nameRegisterTF = new javax.swing.JTextField();
        passwordRegisterTF = new javax.swing.JTextField();
        passwordRegisterLBL = new javax.swing.JLabel();
        emailRegisterTf = new javax.swing.JTextField();
        returnBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        loginPageBTN = new javax.swing.JButton();
        ImageRegisterLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLBL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLBL.setText("RegisterGUI form");
        Panel1.add(titleLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 230, 30));

        registerBTN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerBTN.setText("Register");
        registerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTNActionPerformed(evt);
            }
        });
        Panel1.add(registerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        userNameRegiserLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userNameRegiserLBL.setText("User Name :");
        Panel1.add(userNameRegiserLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        emailRegisterLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailRegisterLBL.setText("Email         :");
        Panel1.add(emailRegisterLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 20));
        Panel1.add(nameRegisterTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 213, -1));
        Panel1.add(passwordRegisterTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 213, -1));

        passwordRegisterLBL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordRegisterLBL.setText("Password  :");
        Panel1.add(passwordRegisterLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
        Panel1.add(emailRegisterTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 213, -1));

        returnBTN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        returnBTN.setText("Return");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });
        Panel1.add(returnBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        exitBTN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        Panel1.add(exitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, -1, -1));

        loginPageBTN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        loginPageBTN.setText("Login Page");
        loginPageBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPageBTNActionPerformed(evt);
            }
        });
        Panel1.add(loginPageBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        ImageRegisterLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisterForm.jpg"))); // NOI18N
        Panel1.add(ImageRegisterLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 548));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPageBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPageBTNActionPerformed
        // TODO add your handling code here:
        FrameForPanels ffp = new FrameForPanels();
        ffp.setVisible(true); // Display the frame
        this.dispose(); // Close the current window

    }//GEN-LAST:event_loginPageBTNActionPerformed

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_returnBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void registerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTNActionPerformed
        // TODO add your handling code here:
        String username = nameRegisterTF.getText();
        String password = passwordRegisterTF.getText();
        String email = emailRegisterTf.getText();

        if (username.isEmpty() || password.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.");
            return;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter("user_credentials.txt", true))) {
            writer.write(username + "," + password + "," + email);
            writer.newLine();
            JOptionPane.showMessageDialog(this, "Registration successful!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving credentials.");
        }
    
    }//GEN-LAST:event_registerBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageRegisterLBL;
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel emailRegisterLBL;
    private javax.swing.JTextField emailRegisterTf;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton loginPageBTN;
    private javax.swing.JTextField nameRegisterTF;
    private javax.swing.JLabel passwordRegisterLBL;
    private javax.swing.JTextField passwordRegisterTF;
    private javax.swing.JButton registerBTN;
    private javax.swing.JButton returnBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel userNameRegiserLBL;
    // End of variables declaration//GEN-END:variables

    void setSelected(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
