/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NewsAndInformationHUB;

import java.util.List;
import java.awt.BorderLayout;
import javax.swing.JInternalFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author arets
 */
public class NewsFeedGUI extends JInternalFrame {
//javax.swing.JFrame
    private JTabbedPane mainFrame;
    private JList<String> articleList, videoList, researchList;
    private NewsFeed newsFeed;

    
/**
* Creates new form NewsFeedGUI
*/
    
    public NewsFeedGUI() {
        initComponents();
    }
    
    public NewsFeedGUI(NewsFeed newsFeed) {
        this();
        this.newsFeed = newsFeed;
        
        SwingUtilities.invokeLater(new Runnable() {
        public void run() {
          //setupTabs();  // Sets up the tabs for articles, videos, and research
            refreshContent();  // Refreshes the content based on the current newsFeed
        }
    });
        

        // Initialize the main tabbed pane
        mainFrame = new JTabbedPane();

        // Initialize tabbed panes for each category
        articleListTab = new JTabbedPane();
        videoListTab = new JTabbedPane();
        researchListTab = new JTabbedPane();

        // Initialize and set up the articles list inside its tabbed pane
        articleList = new JList<>();
        JScrollPane articleScrollPane = new JScrollPane(articleList);
        mainFrame.addTab("Articles", articleScrollPane);

        // Initialize and set up the videos list inside its tabbed pane
        videoList = new JList<>();
        JScrollPane videoScrollPane = new JScrollPane(videoList);
        mainFrame.addTab("Videos", videoScrollPane);

        // Initialize and set up the research list inside its tabbed pane
        researchList = new JList<>();
        JScrollPane researchScrollPane = new JScrollPane(researchList);
        mainFrame.addTab("Research", researchScrollPane);

        // Add each tabbed pane to the main frame
        mainFrame.addTab("ArticleList", articleListTab);
        mainFrame.addTab("VideoList", videoListTab);
        mainFrame.addTab("ResearchList", researchListTab);

        // Add the main frame to the panel
        setLayout(new BorderLayout());
        add(mainFrame, BorderLayout.CENTER);
        refreshContent();
    }

    public void displayArticles(List<String> articles) {
        System.out.println("Displaying articles: " + articles);
        articleList.setListData(articles.toArray(new String[0]));
    }

    public void displayVideos(List<String> videos) {
        System.out.println("Displaying videos: " + videos);
        videoList.setListData(videos.toArray(new String[0]));
    }

    public void displayResearch(List<String> research) {
        System.out.println("Displaying research: " + research);
        researchList.setListData(research.toArray(new String[0]));
    }

    public void refreshContent() {
        System.out.println("Refreshing content");
    List<String> articles = newsFeed.getLatestArticles();
    System.out.println("Articles to display: " + articles);  // Debug statement
    displayArticles(articles);

    List<String> videos = newsFeed.getLatestVideos();
    System.out.println("Videos to display: " + videos);  // Debug statement
    displayVideos(videos);

    List<String> research = newsFeed.getLatestResearch();
    System.out.println("Research to display: " + research);  // Debug statement
    displayResearch(research);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainFrame = new javax.swing.JTabbedPane();
        videoListTab = new javax.swing.JTabbedPane();
        researchListTab = new javax.swing.JTabbedPane();
        articleListTab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainFrame.addTab("VideoList", videoListTab);
        MainFrame.addTab("ResearchList", researchListTab);
        MainFrame.addTab("ArticleList", articleListTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewsFeed newsFeed = new NewsFeed();  // Create a NewsFeed object
                new NewsFeedGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainFrame;
    private javax.swing.JTabbedPane articleListTab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane researchListTab;
    private javax.swing.JTabbedPane videoListTab;
    // End of variables declaration//GEN-END:variables
}
